version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - python/load-cache
      - run:
          command: make development
          name: Install deps
      - python/save-cache
      - run:
          command: source virtualenv_run/bin/activate; make test
          name: Run tests

workflows:
  main:
    jobs:
      - build-and-test
